In [95]:
print('Hello')

Hello


In [96]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [97]:
import seaborn as sns
import numpy as np

In [98]:
mylist = [1,2,3]

In [99]:
np.array(mylist)

array([1, 2, 3])

In [100]:
nested_list = [[1,2],[3,4],[5,6]]

In [101]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [104]:
np.zeros(3)

array([0., 0., 0.])

In [105]:
np.zeros((4,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [106]:
np.zeros((4,12), dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [107]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
np.linspace(0,10,3) # Equally spaced

array([ 0.,  5., 10.])

In [109]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [110]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
np.random.rand(2)

array([0.72199877, 0.93855271])

In [112]:
np.random.rand(3,4)

array([[7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01],
       [7.06630522e-03, 2.30624250e-02, 5.24774660e-01, 3.99860972e-01],
       [4.66656632e-02, 9.73755519e-01, 2.32771340e-01, 9.06064345e-02]])

In [113]:
np.random.randn(3,4) # normal distrubution with variance of 1

array([[-1.47632969,  1.48698096, -0.02445518,  0.35555132],
       [ 0.41701111,  0.83246186, -0.29339915, -0.02983857],
       [ 0.09512578,  0.66465434, -0.1402185 , -0.0331934 ]])

In [114]:
np.random.randint(1,100, (2,3))

array([[ 2, 84, 92],
       [60, 71, 44]])

In [115]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [116]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [117]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[38 18 22 10 10 23 35 39 23  2]


In [118]:
arr.shape

(25,)

In [119]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [120]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [121]:
ranarr.max()

39

In [122]:
ranarr.argmax() # index of the maximum

7

In [123]:
ranarr.argmin()

9

In [124]:
ranarr.dtype

dtype('int64')

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [126]:
arr[8]

8

In [127]:
arr[1:5]

array([1, 2, 3, 4])

In [128]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [129]:
arr[:5]

array([0, 1, 2, 3, 4])

In [130]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [131]:
arr[0:5] =100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [132]:
arr= np.arange(0,11)

In [133]:
slice_of_arr = arr[0:5]

In [134]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [135]:
slice_of_arr[:]=99

In [136]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [137]:
arr_copy =arr.copy() # using copy to avoid impact on the main array/broadcasting

In [138]:
arr_copy [:] =100


In [139]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [140]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [141]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [142]:
arr_2d.shape

(3, 3)

In [143]:
arr_2d[2]

array([35, 40, 45])

In [144]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [145]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [146]:
# Conditional selection
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [147]:
arr= np.arange(0,11)

In [148]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
arr>4 # conditional statement

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [150]:
bool_arr = arr>4

In [151]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [152]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [153]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
arr/arr # in numpy, division by 0 provides a nan

<ipython-input-154-64888de26981>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr # in numpy, division by 0 provides a nan


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [155]:
arr.mean()

5.0

In [156]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [157]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [158]:
np.log(arr)

<ipython-input-158-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [159]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [160]:
arr.max()

10

In [161]:
arr.mean()

5.0

In [162]:
arr_2d = np.arange(0,25).reshape(5,5)

In [163]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
arr_2d.sum()

300

In [165]:
arr_2d.sum(axis =0) #across column

array([50, 55, 60, 65, 70])

In [166]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [167]:
an = np.arange(0,10).reshape(2,5)

In [168]:
an

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [169]:
import numpy as np
import pandas as pd

In [170]:
labels = ['a', 'b', 'c']

mylist =[10,20,30]

arr = np.array([10,20,30])

d = {'a':10, 'b':20, 'c':30}

In [171]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [172]:
pd.Series(data=mylist, index=labels)

a    10
b    20
c    30
dtype: int64

In [173]:
pd.Series(mylist, labels)

a    10
b    20
c    30
dtype: int64

In [174]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [175]:
salesQ1 = pd.Series(data=[250,450,200,150], index=['USA','CHINA','INDIA','BRAZIL'])

In [176]:
salesQ1

USA       250
CHINA     450
INDIA     200
BRAZIL    150
dtype: int64

In [177]:
salesQ2 = pd.Series(data=[260,500,210,100], index=['USA','CHINA','INDIA','BRAZIL'])

In [178]:
salesQ2

USA       260
CHINA     500
INDIA     210
BRAZIL    100
dtype: int64

In [179]:
salesQ2['CHINA']

500

In [180]:
salesQ2[1]

500

In [181]:
salesQ1+salesQ2

USA       510
CHINA     950
INDIA     410
BRAZIL    250
dtype: int64

In [182]:
columns = ['W', 'X', 'Y', 'Z']

In [183]:
index = ['A', 'B', 'C', 'D', 'E']

In [184]:
from numpy.random import randint


In [185]:
np.random.seed(42)
data = randint(-100,100, (5,4))

In [186]:
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]])

In [188]:
df = pd.DataFrame(data, index, columns)

In [189]:
df

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [190]:
df['W']

A     2
B     6
C     2
D    16
E    30
Name: W, dtype: int64

In [191]:
type(df['W'])

pandas.core.series.Series

In [192]:
df[['W', 'Z']]

W   Z
A   2 -86
B   6 -80
C   2 -13
D  16  51
E  30 -99

In [193]:
#creat new column
df['new'] = df['W'] + df['Y']

In [195]:
df.drop('new', axis =1)

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [196]:
df = df.drop('new', axis =1)

In [197]:
df

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [198]:
df.loc['A'] # Find rows

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int64

In [199]:
df.loc[['A', 'E']] # FINS ROWS

W   X   Y   Z
A   2  79  -8 -86
E  30  49 -48 -99

In [200]:
df.iloc[0] # locate with integers

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int64

In [201]:
df.iloc[-1]

W    30
X    49
Y   -48
Z   -99
Name: E, dtype: int64

In [202]:
df.iloc[0:3]

W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80
C  2  21 -26 -13

In [204]:
df.loc[['A', 'C'],['W', 'Y']]

W   Y
A  2  -8
C  2 -26

In [205]:
# CONDITIONAL COMPARISON
df>0

W      X      Y      Z
A  True   True  False  False
B  True  False   True  False
C  True   True  False  False
D  True  False   True   True
E  True   True  False  False

In [206]:
df[df>0]

W     X     Y     Z
A   2  79.0   NaN   NaN
B   6   NaN  88.0   NaN
C   2  21.0   NaN   NaN
D  16   NaN   3.0  51.0
E  30  49.0   NaN   NaN

In [207]:
df

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [209]:
df[df['X']>0]

W   X   Y   Z
A   2  79  -8 -86
C   2  21 -26 -13
E  30  49 -48 -99

In [213]:
df[(df['X']>0) & (df['Y']>1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [214]:
df[(df['X']>0) | (df['Y']>1)]

W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [215]:
df.reset_index()

index   W   X   Y   Z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

In [216]:
new_ind = ['CA', 'NY', 'WY', 'OR', 'CO']

In [217]:
df['States'] = new_ind

In [218]:
df

W   X   Y   Z States
A   2  79  -8 -86     CA
B   6 -29  88 -80     NY
C   2  21 -26 -13     WY
D  16  -1   3  51     OR
E  30  49 -48 -99     CO

In [220]:
df = df.reset_index()

In [221]:
df

index   W   X   Y   Z States
0     A   2  79  -8 -86     CA
1     B   6 -29  88 -80     NY
2     C   2  21 -26 -13     WY
3     D  16  -1   3  51     OR
4     E  30  49 -48 -99     CO

In [223]:
df = df.set_index('States')

In [225]:
df.describe()

W          X          Y          Z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   5 non-null      object
 1   W       5 non-null      int64 
 2   X       5 non-null      int64 
 3   Y       5 non-null      int64 
 4   Z       5 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 412.0+ bytes


In [227]:
df.dtypes

index    object
W         int64
X         int64
Y         int64
Z         int64
dtype: object

In [ ]:
# Handling missing data
